name: Release binaries!

on:
  push:
    tags:
      - "*"

jobs:
  do-on-linux:
    name: Build for ${{ matrix.target }}!
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          [
            aarch64-unknown-linux-gnu,
            armv7-unknown-linux-gnueabihf,
            i686-unknown-linux-gnu,
            x86_64-unknown-linux-gnu,
            mips64-unknown-linux-gnuabi64,
            powerpc-unknown-linux-gnu,
            aarch64-unknown-linux-musl,
            armv7-unknown-linux-musleabihf,
            i686-unknown-linux-musl,
            x86_64-unknown-linux-musl,
            aarch64-linux-android,
            arm-linux-androideabi,
            armv7-linux-androideabi,
            i686-linux-android,
            x86_64-linux-android,
            # i686-pc-windows-gnu,
            x86_64-pc-windows-gnu,
          ]
        include:
          - type: aarch64-unknown-linux-gnu
            target: aarch64-unknown-linux-gnu
            name: aarch64-NtH1M-linux-gnu
            path: target/aarch64-unknown-linux-gnu/release/NtH1M
          - type: armv7-unknown-linux-gnueabihf
            target: armv7-unknown-linux-gnueabihf
            name: armv7-NtH1M-linux-gnueabihf
            path: target/armv7-unknown-linux-gnueabihf/release/NtH1M
          - type: i686-unknown-linux-gnu
            target: i686-unknown-linux-gnu
            name: i686-NtH1M-linux-gnu
            path: target/i686-unknown-linux-gnu/release/NtH1M
          - type: x86_64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
            name: x86_64-NtH1M-linux-gnu
            path: target/x86_64-unknown-linux-gnu/release/NtH1M
          - type: mips64-unknown-linux-gnuabi64
            target: mips64-unknown-linux-gnuabi64
            name: mips64-NtH1M-linux-gnuabi64
            path: target/mips64-unknown-linux-gnuabi64/release/NtH1M
          - type: powerpc-unknown-linux-gnu
            target: powerpc-unknown-linux-gnu
            name: powerpc-NtH1M-linux-gnu
            path: target/powerpc-unknown-linux-gnu/release/NtH1M
          - type: aarch64-unknown-linux-musl
            target: aarch64-unknown-linux-musl
            name: aarch64-NtH1M-linux-musl
            path: target/aarch64-unknown-linux-musl/release/NtH1M
          - type: armv7-unknown-linux-musleabihf
            target: armv7-unknown-linux-musleabihf
            name: armv7-NtH1M-linux-musleabihf
            path: target/armv7-unknown-linux-musleabihf/release/NtH1M
          - type: i686-unknown-linux-musl
            target: i686-unknown-linux-musl
            name: i686-NtH1M-linux-musl
            path: target/i686-unknown-linux-musl/release/NtH1M
          - type: x86_64-unknown-linux-musl
            target: x86_64-unknown-linux-musl
            name: x86_64-NtH1M-linux-musl
            path: target/x86_64-unknown-linux-musl/release/NtH1M
          - type: aarch64-linux-android
            target: aarch64-linux-android
            name: aarch64-NtH1M-linux-android
            path: target/aarch64-linux-android/release/NtH1M
          - type: arm-linux-androideabi
            target: arm-linux-androideabi
            name: arm-NtH1M-linux-androideabi
            path: target/arm-linux-androideabi/release/NtH1M
          - type: armv7-linux-androideabi
            target: armv7-linux-androideabi
            name: armv7-NtH1M-linux-androideabi
            path: target/armv7-linux-androideabi/release/NtH1M
          - type: i686-linux-android
            target: i686-linux-android
            name: i686-NtH1M-linux-android
            path: target/i686-linux-android/release/NtH1M
          - type: x86_64-linux-android
            target: x86_64-linux-android
            name: x86_64-NtH1M-linux-android
            path: target/x86_64-linux-android/release/NtH1M
          # - type: i686-pc-windows-gnu
          #   target: i686-pc-windows-gnu
          #   name: i686-NtH1M-windows-gnu
          #   path: target/i686-pc-windows-gnu/release/NtH1M.exe
          - type: x86_64-pc-windows-gnu
            target: x86_64-pc-windows-gnu
            name: x86_64-NtH1M-windows-gnu
            path: target/x86_64-pc-windows-gnu/release/NtH1M.exe
      
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install the requirements!
        run: |
          sudo apt update && sudo apt install -y mingw-w64 pkg-config libssl-dev openssl

      - name: Install Cross!
        run: cargo install cross

      - name: Build for ${{ matrix.target }}!
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts!
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}


  do-on-windows:
    name: Build for ${{ matrix.target }}!
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        type: [i686-pc-windows-msvc, x86_64-pc-windows-msvc]
        include:
          - type: i686-pc-windows-msvc
            target: i686-pc-windows-msvc
            name: i686-NtH1M-windows-msvc
            path: target/i686-pc-windows-msvc/release/NtH1M.exe
          - type: x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
            name: x86_64-NtH1M-windows-msvc
            path: target/x86_64-pc-windows-msvc/release/NtH1M.exe

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build for ${{ matrix.target }}!
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts!
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}


  do-on-macos:
    name: Build for ${{ matrix.target }}!
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        type:
          [
            aarch64-apple-darwin,
            x86_64-apple-darwin,
            aarch64-apple-ios,
            x86_64-apple-ios,
          ]
        include:
          - type: aarch64-apple-darwin
            target: aarch64-apple-darwin
            name: aarch64-NtH1M-macos
            path: target/aarch64-apple-darwin/release/NtH1M
          - type: x86_64-apple-darwin
            target: x86_64-apple-darwin
            name: x86_64-NtH1M-macos
            path: target/x86_64-apple-darwin/release/NtH1M
          - type: aarch64-apple-ios
            target: aarch64-apple-ios
            name: aarch64-NtH1M-apple-ios
            path: target/aarch64-apple-ios/release/NtH1M
          - type: x86_64-apple-ios
            target: x86_64-apple-ios
            name: x86_64-NtH1M-apple-ios
            path: target/x86_64-apple-ios/release/NtH1M

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build for ${{ matrix.target }}!
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts!
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
